name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0
      - name: Run tests
        run: ./scripts/run_tests.sh
